### PR TITLE
Portfolio Desktop version

### PR DESCRIPTION
**Pull request by kambereBr**
In this pull request I:
- Added CSS style for the desktop responsiveness
- Fixed some issues related to the mobile version responsiveness

### CODE REVIEW

**Review by Bantealem — CHANGES_REQUESTED** [review]
# Status: Change Required
Hi @kambereBr 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- [x] No Linters error
- [x] Correct Gihub flow
- [x] Professional README 

## Required Changes ♻️
- [ ] Please make sure your design is the same as the given Figma design. Currently, the margin of your work section and the button size is not the same as the Figma design. Kindly, fix it
image
Your design
image
Figma design
image
Your design
image
Figma design
image

Your design
image

Figma design
image

Your design 
image
 Figma design
image

Your Design
image

Figma design
image

Your design
image


Figma design
image
- [ ] Please make sure the background color is the same
Your design
image

Figma design
image


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kambereBr** [comment]
Thanks, dear @Bantealem. Need your help please, this pull request shows that it's closed, it seems that I made mistakes when merging another pull request. Now I've pushed new changes to this branch according to your last review, but I can't view those changes here. Your directions will really help me, thanks!

**Comment by Bantealem** [comment]
Hello, @kambereBr Thank you for reaching out to me.
1. Double-check the branch: Make sure you are on the correct branch where you made the new changes. You can use the command git branch to see the current branch and switch to the correct branch using git checkout <branch-name>.

2. Pull the latest changes: Pull the latest changes from the remote repository to ensure you have the most up-to-date version of the branch. Use the command git pull origin <branch-name> to fetch and merge the changes from the remote branch.

3. View the changes: Once you have pulled the latest changes, you should be able to view your new changes in your local repository. 

4 . Resolve any conflicts: If there are conflicts between your new changes and the existing changes, you will need to resolve them. Conflicts occur when Git cannot automatically merge the changes. Open the conflicting files in your code editor and look for sections marked with conflict markers (<<<<<<<, =======, >>>>>>>). Manually edit the files to resolve the conflicts, keeping the changes you want and removing the conflict markers.

5. Commit and push your changes: Once you have resolved any conflicts, stage and commit your changes using the command git commit -m "Your commit message". Then push your changes to the remote repository using git push origin <branch-name>.

I hope this will help you. 

Happy coding.

**Comment by kambereBr** [comment]
Thanks, @Bantealem, let me proceed as you've written above.

**Comment by Bantealem** [comment]
You are welcome @kambereBr

**Comment by kambereBr** [comment]
Dear @Bantealem, I've proceeded as you've suggested and I've pushed my changes. Here is the screenshot of my recent push

microverse-desktop-version

But I can't still see all updates in this pull request. 
Thanks again for your help!

**Comment by Bantealem** [comment]
Kindly try the second option.

**Comment by kambereBr** [comment]
Dear @Bantealem,  The problem is that yesterday I made a mistake accidentally merging this pull request reason why it says that this pull request is already closed as it is shown in the image below
microverse-pull-request-4

I'd to ask you, with your permission if I can create a new pull request in order to avoid this issue. 

Thanks!

**Comment by kambereBr** [comment]
Thanks a lot @Bantealem !

**Comment by Bantealem** [comment]
I can't guarantee you since the reviewer may be another person. But you can explain the situation when you request a review. @kambereBr

**Comment by kambereBr** [comment]
Thanks @Bantealem, I explained my issue to the code reviewer and he reviewed my new pull request. After applying some changes, the pull request was been authorized to be merged. Thanks again for your help

**Pull request merged**
